[package]
name = "network"
version = "0.1.0"
edition = "2024"

[lib]
name = "network"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
pcap = "2.2.0"
pnet = "0.35.0"
httparse = "1.10.1"
dns-parser = "0.8.0"
